Global:
  use_gpu: true
  epoch_num: 130
  log_smooth_window: 10
  print_batch_step: 10
  save_model_dir: ./output/re_ablation_v2/re_layoutxlm_xfund_zh_v4_udml
  save_epoch_step: 2000
  eval_batch_step:
  - 0
  - 19
  cal_metric_during_train: false
  save_inference_dir: null
  use_visualdl: false
  seed: 2022
  infer_img: ppstructure/docs/vqa/input/zh_val_21.jpg
  save_res_path: ./output/re/xfund_zh/with_gt
Architecture:
  model_type: vqa
  name: DistillationModel
  algorithm: Distillation
  Models:
    Teacher:
      pretrained: null
      freeze_params: false
      return_all_feats: true
      model_type: vqa
      algorithm: LayoutXLM
      Transform: null
      Backbone:
        name: LayoutXLMForRe
        pretrained: pretrain_models/layoutxlm-base-uncased_wo_backbone/
        checkpoints: null
    Student:
      pretrained: null
      freeze_params: false
      return_all_feats: true
      model_type: vqa
      algorithm: LayoutXLM
      Transform: null
      Backbone:
        name: LayoutXLMForRe
        pretrained: pretrain_models/layoutxlm-base-uncased_wo_backbone/
        checkpoints: null
Loss:
  name: CombinedLoss
  loss_config_list:
  - DistillationLossFromOutput:
      weight: 1.0
      model_name_list:
      - Student
      - Teacher
      key: loss
      reduction: mean
  - DistillationSerDistanceLoss:
      weight: 0.5
      mode: l2
      model_name_pairs:
      - - Student
        - Teacher
      key: hidden_states_5
      name: loss_5
  - DistillationSerDistanceLoss:
      weight: 0.5
      mode: l2
      model_name_pairs:
      - - Student
        - Teacher
      key: hidden_states_8
      name: loss_8
Optimizer:
  name: AdamW
  beta1: 0.9
  beta2: 0.999
  clip_norm: 10
  lr:
    learning_rate: 5.0e-05
    warmup_epoch: 10
  regularizer:
    name: L2
    factor: 0.0
PostProcess:
  name: DistillationRePostProcess
  model_name:
  - Student
  - Teacher
  key: null
Metric:
  name: DistillationMetric
  base_metric_name: VQAReTokenMetric
  main_indicator: hmean
  key: Student
Train:
  dataset:
    name: SimpleDataSet
    data_dir: C:\Users\ratam\Downloads\test_ppocrlabel\PaddleOCR\train_data\train\image
    label_file_list:
    - C:\Users\ratam\Downloads\test_ppocrlabel\PaddleOCR\train_data\train\train.txt
    ratio_list:
    - 1.0
    transforms:
    - DecodeImage:
        img_mode: RGB
        channel_first: false
    - VQATokenLabelEncode:
        contains_re: true
        algorithm: LayoutXLM
        class_path: train_data/XFUND/class_list_xfun.txt
        use_textline_bbox_info: true
        order_method: ppocr-order
    - VQATokenPad:
        max_seq_len: 512
        return_attention_mask: true
    - VQAReTokenRelation: null
    - VQAReTokenChunk:
        max_seq_len: 512
    - Resize:
        size:
        - 224
        - 224
    - NormalizeImage:
        scale: 1
        mean:
        - 123.675
        - 116.28
        - 103.53
        std:
        - 58.395
        - 57.12
        - 57.375
        order: hwc
    - ToCHWImage: null
    - KeepKeys:
        keep_keys:
        - input_ids
        - bbox
        - attention_mask
        - token_type_ids
        - image
        - entities
        - relations
  loader:
    shuffle: true
    drop_last: false
    batch_size_per_card: 2
    num_workers: 4
    collate_fn: ListCollator
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: C:\Users\ratam\Downloads\test_ppocrlabel\PaddleOCR\train_data\val\image
    label_file_list:
    - C:\Users\ratam\Downloads\test_ppocrlabel\PaddleOCR\train_data\val\val.txt
    transforms:
    - DecodeImage:
        img_mode: RGB
        channel_first: false
    - VQATokenLabelEncode:
        contains_re: true
        algorithm: LayoutXLM
        class_path: train_data/XFUND/class_list_xfun.txt
        use_textline_bbox_info: true
        order_method: ppocr-order
    - VQATokenPad:
        max_seq_len: 512
        return_attention_mask: true
    - VQAReTokenRelation: null
    - VQAReTokenChunk:
        max_seq_len: 512
    - Resize:
        size:
        - 224
        - 224
    - NormalizeImage:
        scale: 1
        mean:
        - 123.675
        - 116.28
        - 103.53
        std:
        - 58.395
        - 57.12
        - 57.375
        order: hwc
    - ToCHWImage: null
    - KeepKeys:
        keep_keys:
        - input_ids
        - bbox
        - attention_mask
        - token_type_ids
        - image
        - entities
        - relations
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 8
    num_workers: 8
    collate_fn: ListCollator
profiler_options: null
